server:
  port: 1111

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:postgres}?currentSchema=${POSTGRES_SCHEMA:parking}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:postgres}
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    changeLog: classpath:db/master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

management:
  server:
    port: 5660
  endpoints:
    port: 5660
    web:
      basePath: /
      exposure:
        include: "*"
        exclude: metrics
      path-mapping:
        prometheus: metrics
    metrics:
      export:
        prometheus:
          enabled: true
