apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: parking
spec:
  rules:
  - host: spda-parking.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 5678
      # - path: /
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: backend-service
      #       port:
      #         number: 5678
